const PROTO: string = "https"
const DOMAIN: string = "labdev1002.com"
export const PRODUCER_URL = `${PROTO}://producer.${DOMAIN}` // :8888
export const FIRST_CONSUMER_URL = `${PROTO}://primary-consumer.${DOMAIN}` // :8000
export const BLUE_CONSUMER_URL = `${PROTO}://blue-consumer.${DOMAIN}` // :8001
export const ORANGE_CONSUMER_URL = `${PROTO}://orange-consumer.${DOMAIN}`   // :8002
export const GREEN_CONSUMER_URL = `${PROTO}://green-consumer.${DOMAIN}` // :8003
export const FIRST_GROUP = `first-group`
export const POLLING_INTERVAL = 1000
export const PROVISIONER_URL = `${PROTO}://provisioner.${DOMAIN}` // :8081
export const AUTHORIZER_URL = `${PROTO}://authorizer.${DOMAIN}` // :8082
export const NOTIFIER_URL = `${PROTO}://notifier.${DOMAIN}` // :8083
export const DLQ_URL = `${PROTO}://error-consumer.${DOMAIN}` // :8084